site_name: "mkdocs-shadcn"
site_url: "https://asiffer.github.io/mkdocs-shadcn"
site_description: "Documentation that also shines"
site_author: "Alban Siffer <31479857+asiffer@users.noreply.github.com>"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/asiffer/mkdocs-shadcn"
theme:
  name: shadcn
  pygments_style: "dracula"

nav:
  - "Welcome": index.md
  - install.md
  - extensions.md

markdown_extensions:
  admonition:
  codehilite:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  # tables:
  # toc:
  # pymdownx.highlight:
  # pymdownx.superfences:
