name: Playwright Tests

on:
  pull_request:

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Ensure browsers are installed
      run: uv run playwright install --with-deps chromium
    
    - name: Run your tests
      run: uv run pytest --tracing=retain-on-failure
